"""
Report Generator
----------------
Compiles all 5 agent outputs into a structured Markdown Judgement Report.
Includes executive summary, detailed scores, fact-check log, and final recommendation.
"""

from datetime import datetime


def _pass_fail(state: dict) -> str:
    """Determine overall Pass/Fail recommendation based on agent results."""
    consistency = state.get("consistency_result", {}).get("score", 0)
    fabrication = state.get("authenticity_result", {}).get("fabrication_probability", 100)
    grammar = state.get("grammar_result", {}).get("rating", "Low")

    grammar_score = {"High": 3, "Medium": 2, "Low": 1}.get(grammar, 1)

    # Pass if: consistency >= 60, fabrication < 40, grammar not Low
    if consistency >= 60 and fabrication < 40 and grammar_score >= 2:
        return "✅ PASS"
    elif consistency >= 40 and fabrication < 60:
        return "⚠️ CONDITIONAL PASS"
    else:
        return "❌ FAIL"


def _format_fact_check_log(factcheck: dict) -> str:
    """Format the fact-check results into a readable log."""
    lines = []

    verified = factcheck.get("verified_claims", [])
    if verified:
        lines.append("#### ✅ Verified Claims")
        for i, claim in enumerate(verified, 1):
            if isinstance(claim, dict):
                lines.append(f"{i}. **{claim.get('claim', 'N/A')}**")
                lines.append(f"   - Confidence: {claim.get('confidence', 'N/A')}")
                lines.append(f"   - {claim.get('explanation', '')}")
            else:
                lines.append(f"{i}. {claim}")
        lines.append("")

    unverified = factcheck.get("unverified_claims", [])
    if unverified:
        lines.append("#### ⚠️ Unverified Claims")
        for i, claim in enumerate(unverified, 1):
            if isinstance(claim, dict):
                lines.append(f"{i}. **{claim.get('claim', 'N/A')}**")
                lines.append(f"   - Reason: {claim.get('reason', 'N/A')}")
                lines.append(f"   - Risk Level: {claim.get('risk_level', 'N/A')}")
            else:
                lines.append(f"{i}. {claim}")
        lines.append("")

    flagged = factcheck.get("flagged_claims", [])
    if flagged:
        lines.append("#### 🚩 Flagged Claims (Potentially Incorrect)")
        for i, claim in enumerate(flagged, 1):
            if isinstance(claim, dict):
                lines.append(f"{i}. **{claim.get('claim', 'N/A')}**")
                lines.append(f"   - {claim.get('explanation', '')}")
            else:
                lines.append(f"{i}. {claim}")
        lines.append("")

    if not lines:
        lines.append("No factual claims were identified for verification.")

    return "\n".join(lines)


def _format_red_flags(authenticity: dict) -> str:
    """Format authenticity red flags."""
    flags = authenticity.get("red_flags", [])
    if not flags:
        return "No red flags detected."

    lines = []
    for i, flag in enumerate(flags, 1):
        if isinstance(flag, dict):
            lines.append(f"{i}. **{flag.get('flag', 'N/A')}** [{flag.get('severity', 'N/A')}]")
            evidence = flag.get("evidence", "")
            if evidence:
                lines.append(f"   - Evidence: {evidence}")
        else:
            lines.append(f"{i}. {flag}")

    return "\n".join(lines)


def generate_report(state: dict) -> str:
    """
    Generate a comprehensive Markdown Judgement Report from pipeline state.

    Args:
        state: The full PaperState dict with all agent results.

    Returns:
        A formatted Markdown string.
    """
    # Extract data
    title = state.get("title", "Unknown Paper")
    authors = state.get("authors", [])
    published = state.get("published", "Unknown")
    arxiv_id = state.get("arxiv_id", "Unknown")
    arxiv_url = state.get("arxiv_url", "")

    consistency = state.get("consistency_result", {})
    grammar = state.get("grammar_result", {})
    novelty = state.get("novelty_result", {})
    factcheck = state.get("factcheck_result", {})
    authenticity = state.get("authenticity_result", {})

    verdict = _pass_fail(state)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build report
    report = f"""# 📋 Judgement Report

> **Automated Peer Review — Generated by Hivel**
> Date: {timestamp}

---

## 📄 Paper Details

| Field | Value |
|-------|-------|
| **Title** | {title} |
| **Authors** | {', '.join(authors[:5])}{'...' if len(authors) > 5 else ''} |
| **Published** | {published} |
| **arXiv ID** | [{arxiv_id}]({arxiv_url}) |

---

## 🏆 Executive Summary

### Recommendation: {verdict}

| Metric | Score |
|--------|-------|
| **Consistency Score** | {consistency.get('score', 'N/A')} / 100 |
| **Grammar Rating** | {grammar.get('rating', 'N/A')} |
| **Novelty Index** | {novelty.get('novelty_index', 'N/A')} |
| **Fabrication Risk** | {authenticity.get('fabrication_probability', 'N/A')}% ({authenticity.get('risk_level', 'N/A')}) |

---

## 1. 🔗 Consistency Analysis

**Score: {consistency.get('score', 'N/A')} / 100**

{consistency.get('reasoning', 'No analysis available.')}

**Strengths:**
{chr(10).join(f'- {s}' for s in consistency.get('strengths', ['None identified.']))}

**Weaknesses:**
{chr(10).join(f'- {w}' for w in consistency.get('weaknesses', ['None identified.']))}

**Alignment Issues:**
{chr(10).join(f'- {a}' for a in consistency.get('alignment_issues', ['None found.'])) if consistency.get('alignment_issues') else '- None found.'}

---

## 2. ✍️ Grammar & Language

**Rating: {grammar.get('rating', 'N/A')}**

{grammar.get('overall_assessment', 'No assessment available.')}

**Issues Found:**
"""

    issues = grammar.get("issues", [])
    if issues:
        for issue in issues:
            if isinstance(issue, dict):
                report += f"- **[{issue.get('type', 'general')}]** {issue.get('description', 'N/A')} _(severity: {issue.get('severity', 'N/A')})_\n"
            else:
                report += f"- {issue}\n"
    else:
        report += "- No significant issues found.\n"

    suggestions = grammar.get("suggestions", [])
    report += f"""
**Suggestions:**
{chr(10).join(f'- {s}' for s in suggestions) if suggestions else '- No suggestions.'}

---

## 3. 🔬 Novelty Assessment

**Novelty Index: {novelty.get('novelty_index', 'N/A')}**

**Core Contribution:** {novelty.get('core_contribution', 'Not identified.')}

{novelty.get('assessment', 'No assessment available.')}

**Unique Aspects:**
{chr(10).join(f'- {u}' for u in novelty.get('unique_aspects', ['None identified.']))}

**Similar Work Found:**
"""

    comparisons = novelty.get("similar_work_comparison", [])
    if comparisons:
        for comp in comparisons:
            if isinstance(comp, dict):
                report += f"- **{comp.get('paper', 'N/A')}**: {comp.get('relationship', 'N/A')}\n"
            else:
                report += f"- {comp}\n"
    else:
        report += "- No similar work comparison available.\n"

    report += f"""
---

## 4. 🔍 Fact-Check Log

{_format_fact_check_log(factcheck)}

**Summary:** {factcheck.get('log', 'No fact-check summary available.')}

---

## 5. 🛡️ Authenticity & Fabrication Assessment

**Fabrication Probability: {authenticity.get('fabrication_probability', 'N/A')}%**
**Risk Level: {authenticity.get('risk_level', 'N/A')}**

{authenticity.get('assessment', 'No assessment available.')}

**Red Flags:**
{_format_red_flags(authenticity)}

**Positive Indicators of Authenticity:**
{chr(10).join(f'- {p}' for p in authenticity.get('positive_indicators', ['None identified.']))}

**Reproducibility:** {authenticity.get('reproducibility_assessment', 'Not assessed.')}

---

## 📊 Final Verdict

| Metric | Result |
|--------|--------|
| Consistency | {consistency.get('score', 'N/A')}/100 |
| Grammar | {grammar.get('rating', 'N/A')} |
| Novelty | {novelty.get('novelty_index', 'N/A')} |
| Fact-Check | {len(factcheck.get('verified_claims', []))} verified · {len(factcheck.get('unverified_claims', []))} unverified · {len(factcheck.get('flagged_claims', []))} flagged |
| Fabrication Risk | {authenticity.get('fabrication_probability', 'N/A')}% |
| **Recommendation** | **{verdict}** |

---

*Report generated by Hivel*
"""

    return report
